version: '3.8'
services:
  user-liquibase:
    build: ./user-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_URL: "${DB_URL}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_SCHEMA: "${DB_SCHEMA}"
      SKIP_MIGRATION: "false"

  user-app:
    build: ./user-impl
    container_name: user-app
    ports:
      - "9000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_DATASOURCE_URL: "${DB_URL}?currentSchema=${DB_SCHEMA}"
      SPRING_DATASOURCE_USERNAME: "${DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: "${DB_SCHEMA}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_SERVERS}"
      SPRING_LIQUIBASE_ENABLED: "false"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      user-liquibase:
        condition: service_completed_successfully