server:
  port: 8070

spring:
  application:
    name: user-impl
  datasource:
    url: jdbc:postgresql://localhost:5511/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:database-changelog.xml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: "3MZ7BDeA3j4p9GXrHYFYNSKfMUs_yxjQPNx#JhFEjj#b7@7mBN#Ifatux4q0bbSMW345A_dRFu0tG3yqdrHCAKVupami2FIIpk3K"

springdoc:
  show-login-endpoint: true
  show-pre-authorize: true